apiVersion: apps/v1
kind: Deployment
metadata:
   name: java-app-v2
   labels:
     app: java-app
spec:
   replicas: 1
   selector:
      matchLabels:
        app: java-app
        version: v2.0
   template:
      metadata:
        labels:
          app: java-app
          version: 2.0
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9101"
      spec:
        containers:
        - name: java-app
          image: chaitu465/k8s-java-deployment-app:2.0
          ports:
          - name: http
            containerPort: 9898
          - name: probe
            containerPort: 8686
          env:
          - name: VERSION
            value: v2.0