apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: java-cluster-svc-readonlybinding
   namespace: chaitanya
subjects:
 - kind: ServiceAccount
   name: java-pod-reader
   namespace: chaitanya
roleRef:
  kind: ClusterRole
  name: cluster-services-reader
  apiGroup: "rbac.authorization.k8s.io"