apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: java-cb-pod-readerbinding
subjects:
- kind: ServiceAccount
  name: java-pod-reader
  apiGroup: ""
  namespace: chaitanya
roleRef:
  kind: ClusterRole
  name: cluster-secrets
  apiGroup: "rbac.authorization.k8s.io"
